### ISSUE TITLE
Error when using !youtube command

### ISSUE THREAD

**Issue by burgrr** [Gravebot/Gravebot#254]
"Error: Project 545509771692 has been scheduled for deletion and cannot be used for API calls. Visit https://console.developers.google.com/iam-admin/projects?pendingDeletion=true to undelete the project." is returned when using the !youtube command. Untested with other commands. Going to the link it provides gives nothing

**Comment by RoobieBoobieee** [comment]
Try generating a new api key

**Comment by Gravestorm** [comment]
Should be fixed, thanks for noticing and sorry for the inconvenience.

**Comment by burgrr** [comment]
still doesnt work. gives "Please setup YOUTUBE_KEY in config.js to use the !youtube command."
